{% set name = "clisops" %}
{% set version = "0.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 541f36d12553454d9c9335c4eefce292c9c7b9b46cce51df45649ccbcf1b918f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python >=3.6
    - numpy >=1.16
    - xarray >=0.15
    - pandas >=1.0.3
    - cftime >=1.4.1
    - netCDF4 >=1.4
    - poppler >=0.67
    - shapely >=1.6
    - geopandas >=0.7
    - xesmf >=0.5.2
    - dask >=2.6.0
    - bottleneck >=1.3.1,<1.4
    - pyproj >=2.5
    - roocs-utils >=0.2.1
    - requests >=2.0
    - cf_xarray >=0.3.1
    - pygeos >=0.8

test:
  imports:
    - clisops

about:
  home: https://pypi.org/project/clisops/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: clisops - climate simulation operations

  description: |
    The clisops package (pronounced "clie-sops") provides a python library for running
    data-reduction operations on xarray data sets or files
    that can be interpreted by xarray. These basic operations (subsetting, averaging and
    regridding) are likely to work where data structures are NetCDF-centric, such as those
    found in ESGF data sets.
  doc_url: https://clisops.readthedocs.io/en/latest/
  dev_url: https://github.com/roocs/clisops

extra:
  recipe-maintainers:
    - ellesmith88
    - Zeitsperre
    - agstephens
    - cehbrecht
