{% set name = "clisops" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 542bf60bfc6e42464874057fe269572390fc7b99160566baa4dd2b94dbc5f7ce

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - pytest-runner
  run:
    - python
    - numpy >=1.16
    - xarray >=0.15
    - pandas >=1.0.3
    - cftime >=1.0.4
    - netCDF4 >=1.4
    - poppler >=0.67
    - fiona >=1.8
    - geojson >=2.5.0
    - shapely >=1.6
    - geopandas >=0.7
    - dask >=2.6.0
    - bottleneck >=1.3.1,<1.4
    - pyproj >=2.5
    - rtree >=0.9
    - udunits2 >=2.2
    - roocs-utils >= 0.1.4

test:
  imports:
    - clisops

about:
  home: https://pypi.org/project/clisops/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: clisops - climate simulation operations

  description: |
    The clisops package (pronounced "clie-sops") provides a python library for running
    data-reduction operations on xarray data sets or files
    that can be interpreted by xarray. These basic operations (subsetting, averaging and
    regridding) are likely to work where data structures are NetCDF-centric, such as those
    found in ESGF data sets.
  doc_url: https://clisops.readthedocs.io/en/latest/
  dev_url: https://github.com/roocs/clisops

extra:
  recipe-maintainers:
    - ellesmith88
    - Zeitsperre
    - agstephens
    - cehbrecht
