{% set name = "clisops" %}
{% set version = "0.16.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1a9755145249429ddb1e5398123936cb89b02bade737106e4dca5257ac82a372

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.10.1,<4.0
    - pip
  run:
    - python >={{ python_min }}
    - aiohttp # Needed for HTTPFileSystem
    - bottleneck >=1.3.1
    - cartopy >=0.23
    - cf_xarray >=0.8.6
    - cftime >=1.4.1
    - dask >=2023.6.0
    - filelock >=3.15.4
    - fsspec >=2023.9.0
    - geopandas >=1.0
    - jinja2 >=2.11
    - loguru >=0.5.3
    - numpy >=1.24.0
    - packaging >=23.2
    - pandas >=1.5.3
    - platformdirs >=4.0
    - pooch >=1.8.0
    - pyproj >=3.3.0
    - requests # Needed for HTTPFileSystem
    - roocs-grids >=0.1.2
    - scipy >=1.11.0
    - shapely >=2.0
    - xarray >=2025.1.1
    - zarr >=2.13.0
  run_constrained:
    - xesmf >=0.8.2

test:
  imports:
    - clisops
  requires:
    - netCDF4 >=1.4
    - pip
    - python {{ python_min }}
    - pytest >=8.0.0
    - pytest-loguru >=0.3.0
    - pytest-xdist >=3.2
  source_files:
    - pyproject.toml
    - tests
  commands:
    - pip check
    - pytest tests --numprocesses=2

about:
  home: https://pypi.org/project/clisops/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: CLISOPS - Climate simulation operations.
  description: |
    The clisops package (pronounced "clie-sops") provides a python library for running
    data-reduction operations on xarray data sets or files that can be interpreted by xarray.
    These basic operations (subsetting, averaging and regridding) are likely to work
    where data structures are NetCDF-centric, such as those found in ESGF data sets.
  doc_url: https://clisops.readthedocs.io/en/latest/
  dev_url: https://github.com/roocs/clisops

extra:
  recipe-maintainers:
    - Zeitsperre
    - agstephens
    - cehbrecht
