{% set name = "clisops" %}
{% set version = "0.16.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 85ef60dd40d334138b89f62b158930e572480f9dcb6b6a077e3f89ab8b77281d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.9,<4.0
    - pip
  run:
    - python >={{ python_min }}
    - aiohttp # Needed for HTTPFileSystem
    - bottleneck >=1.3.1
    - cartopy >=0.23
    - cf_xarray >=0.8.6
    - cftime >=1.4.1
    - dask >=2023.6.0
    - filelock >=3.15.4
    - fsspec >=2023.9.0
    - geopandas >=0.14.0
    - jinja2 >=2.11
    - loguru >=0.5.3
    - numpy >=1.23.0,<2.1
    - packaging >=23.2
    - pandas >=1.5.0
    - platformdirs >=4.0
    - pooch >=1.8.0
    - pyproj >=3.3.0
    - requests # Needed for HTTPFileSystem
    - roocs-grids >=0.1.2
    - scipy >=1.9.0
    - shapely >=1.9
    - xarray >=2022.9.0
    - zarr
  run_constrained:
    - xesmf >=0.8.2

test:
  imports:
    - clisops
  requires:
    - netCDF4 >=1.4
    - pip
    - python {{ python_min }}
    - pytest >=8.0.0
    - pytest-loguru >=0.3.0
    - pytest-xdist >=3.2
  source_files:
    - tests
  commands:
    - pip check
    - pytest tests

about:
  home: https://pypi.org/project/clisops/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: CLISOPS - Climate simulation operations.
  description: |
    The clisops package (pronounced "clie-sops") provides a python library for running
    data-reduction operations on xarray data sets or files that can be interpreted by xarray.
    These basic operations (subsetting, averaging and regridding) are likely to work
    where data structures are NetCDF-centric, such as those found in ESGF data sets.
  doc_url: https://clisops.readthedocs.io/en/latest/
  dev_url: https://github.com/roocs/clisops

extra:
  recipe-maintainers:
    - Zeitsperre
    - agstephens
    - cehbrecht
